#ifndef IG20260728105828
#define IG20260728105828

typedef enum ContextId
{
    CONTEXT_INPUT_FIRST,
    CONTEXT_ACTION_TYPE,
    CONTEXT_STONE_TYPE,
    CONTEXT_POSITION,
    CONTEXT_DIRECTION,
    CONTEXT_AMOUNT,
    CONTEXT_SIZE,
    CONTEXT_GLOBAL,
    CONTEXT_COUNT,
} ContextId;

#endif

