#ifndef IG20260430175417
#define IG20260430175417

typedef enum AppStateId
{
    APP_STATE_CHOOSE_BOARD_SIZE,
    APP_STATE_FIRST_TURN,
    APP_STATE_SECOND_TURN,
    APP_STATE_NORMAL_TURN,
    APP_STATE_TURN_UNDO,
    APP_STATE_TURN_REDO,
    APP_STATE_TURN_RESET,
    APP_STATE_GAME_END,
} AppStateId;

#endif
